version: 2022.02.13
slug: zhaws
name: ZHA WS
description: Control a Zigbee network with ZHAWS
url: https://github.com/home-assistant/hassio-addons/tree/master/zhaws
arch:
  - amd64
  - i386
  - armhf
  - armv7
  - aarch64
discovery:
  - zhaws
hassio_api: true
homeassistant: 2021.2.0b0
#image: homeassistant/{arch}-addon-zhaws
init: false
options:
  device: null
  log_level: info
  radio_type: null
  radio_baudrate: null
  radio_flow_control: null
  network_auto_start: true
  enable_quirks: true
ports:
  8001/tcp: null
ports_description:
  8001/tcp: ZHAWS communication
schema:
  device: device(subsystem=tty)
  log_level: list(silly|debug|verbose|http|info|warn|error)?
  radio_type: list(ezsp|xbee|deconz|znp|zigate)
  radio_baudrate: list(2400|4800|9600|14400|19200|38400|57600|115200|128000|256000)
  radio_flow_control: list(hardware|software)
  network_auto_start: bool
  enable_quirks: bool
stage: stable
startup: services
